---
color:
  solarized:
    tmux: &tmuxDefault solarized
  gruvbox:
    tmux: gruvbox
  dracula:
    tmux: dracula

tmux_terminal_features:
  alacritty:
    term_name: alacritty
    features: "clipboard:ccolour:cstyle:focus:title:RGB:256:usstyle:extkeys"
    overrides: "Tc:RGB"
  kitty:
    term_name: xterm-kitty
    features: "clipboard:ccolour:cstyle:focus:title:RGB:256:usstyle:extkeys"
    # Kitty supports RGB and 256 colors, underscore style and color
