version: "3"
services:
  dotfiles:
    build:
      context: .
    image: yadr
    volumes:
      - ./:/root/.yadr/
      - vim_plug:/root/.yadr/root/vim/plugged/
      - prezto:/root/.zprezto/
volumes:
  vim_plug:
  prezto:
