version: "3"
name: yadr
services:
  dotfiles:
    build:
      context: .
    image: yadr
    volumes:
      - ./:/root/.yadr/
      - plugged:/root/.vim/plugged
      - zprezto:/root/.zprezto
volumes:
  plugged:
  zprezto:
