version: "3"
services:
  dotfiles:
    build:
      context: .
    image: yadr
    volumes:
      - ./:/root/.yadr/
      - /tmp/plugged-yadr:/root/.yadr/root/vim/plugged/
      - ~/.cache/dotfiles/zprezto:/root/.zprezto/

