{{- /*
  vim:ft=yaml.gotmpl:
    */ -}}

---

#
# ZSH shell
#

# Prezto
'.zprezto':
  url: 'https://github.com/sorin-ionescu/prezto.git'
  type: 'git-repo'
  refreshPeriod: '168h' # 7 days
  clone:
    args:
      - '--depth=1'
      - '--recursive'
      - '--shallow-submodules'
  pull:
    args:
      - '--recurse-submodules=yes'

# Oh my Zsh
'.oh-my-zsh':
  url: 'https://github.com/ohmyzsh/ohmyzsh/archive/refs/heads/master.tar.gz'
  type: 'archive'
  stripComponents: 1
  refreshPeriod: '720h' # 30 days
