{{- /*
  vim:ft=yaml.gotmpl:
    */ -}}

{{- $releaseURLS := joinPath .chezmoi.homeDir ".backup/chezmoi" "gitHubLatestRelease.yaml" -}}
{{- if stat $releaseURLS -}}
{{-   $releaseURLS = include $releaseURLS | fromYaml -}}
{{- else -}}
{{-   $releaseURLS = .external -}}
{{- end -}}
---

# Nerd Fonts
{{- $url_download := $releaseURLS.fonts.url }}
{{- $fontPath := "" }}
{{- if eq .chezmoi.os "linux" }}
{{-   $fontPath = ".local/share/fonts" }}
{{- else if eq .chezmoi.os "darwin" }}
{{-   $fontPath = "Library/Fonts" }}
{{- end }}
{{- range (list "InconsolataLGC" "Meslo") }}
'{{- joinPath $fontPath (substr 0 1 . | lower) . -}}':
  url: '{{- $url_download -}} / {{- . -}} .zip'
  type: 'archive'
  executable: true
  refreshPeriod: '720h' # 30 days
  exclude:
    - '*Windows*'
    - '*Mono*'
{{- end }}
    - '*DZ*'
    - '*LG [LM]*'


# Prezto
'.zprezto':
  url: 'https://github.com/sorin-ionescu/prezto.git'
  type: 'git-repo'
  refreshPeriod: '168h' # 7 days
  clone:
    args:
      - '--depth=1'
      - '--recursive'
      - '--shallow-submodules'
  pull:
    args:
      - '--recurse-submodules=yes'
