---
'.zprezto':
  url: 'https://github.com/sorin-ionescu/prezto.git'
  type: 'git-repo'
  refreshPeriod: '168h' # 7 days
  clone:
    args:
      - '--depth=1'
      - '--shallow-submodules'
      - '--recursive'
  pull:
    args:
      - '--recurse-submodules=yes'
