---
color:
  solarized: &defaultColors
    tmux: &tmuxDefault 'solarized'
  gruvbox:
    tmux: 'gruvbox'
  dracula:
    tmux: 'dracula'

sayings:
  - phrase: "So long and thanks for all the fish."
    author: "Douglas Adams"
  - phrase: "Good morning! And in case I don't see ya, good afternoon, good evening and goodnight."
    author: "Truman Burbank"

# PS: Only tmux >= 3.1 supports terminal-features
tmux_terminal_features:
  01_tmux:
    term_name: 'tmux*'
    features: 'title'
    overrides: 'Ss=\E[%p1%d q:Se=\E[3 q' # reset and set cursor shape
  02_xterm:
    term_name: 'xterm*'
    overrides: 'Tc:RGB:smxx=\E[9m' # enable strikethrough text
  03_kitty:
    term_name: 'xterm-kitty'
    features:  'Tc:RGB:256:usstyle:extkeys'
    # Kitty supports RGB and 256 colors, underscore style and color
    # overrides: 'Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'
    # underscore colours - needs tmux-3.0
  04_alacritty:
    term_name: 'alacritty'
    features:  'clipboard:ccolour:cstyle:focus:title:RGB:256:usstyle:extkeys'
    overrides: 'Tc:RGB'

