name: CI

on:
  push:
    branches:
      - "main"
      - "mine"
  pull_request:
    branches:
      - "main"
      - "friends"

jobs:
  clone-and-install:

    runs-on: ubuntu-latest

    env:
      CODESPACES: true

    steps:
    - uses: actions/checkout@v3

    - name: install
      run: ./install.sh

    - name: chezmoi data
      run: './root/bin/chezmoi data --format yaml'

    - name: chezmoi managed
      run: './root/bin/chezmoi managed -i all'

    - name: installed font files
      run: 'ls -lha ~/.local/share/fonts/**/*/'

