name: ci

on:
  push:
  pull_request:

jobs:
  clone-and-install:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/vscode/devcontainers/base:ubuntu
      env:
        CODESPACES: true
    steps:
      - uses: actions/checkout@v2
      - run: ./install.sh
      - name: chezmoi data
        run: './bin/chezmoi data --format yaml'
      - name: chezmoi managed
        run: './bin/chezmoi managed -i all'
      - name: installed font files
        run: 'ls -lha ~/.local/share/fonts/**/*'
